### PR TITLE
Fix environment

### PR DESCRIPTION
**Pull request by briandevvn**
1. Change baseImage to fix missing libgomp.so file
2. Fix missing pandas package

### CODE REVIEW

**Comment by briandevvn** [comment]
I have already fixed the missing environment in this issue: https://github.com/MG-Microsoft/MLOps_Workshop/issues/4
Please review the commit

**Comment by neilmca-inc** [comment]
This was the only way to complete video 7 from the YouTube series so I'd suggest this is merged into the main branch asap as I had the same issue today with pandas

**Comment by briandevvn** [comment]
Thanks, but MG has not responded my email yet :))

**Comment by MG-Cafe** [comment]
Thank you @gnvml and @neilmca-inc . The request will be merged! Appreciate your inputs! :)

**Pull request merged**
